services:

  postgres:
    image: postgres:17
    container_name: ecommerce_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: ecommerce_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl:
    build: .
    container_name: ecommerce_etl

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - .:/app

    working_dir: /app

    command: python scripts/main.py

volumes:
  postgres_data: